### ISSUE TITLE
HLS seeking

### ISSUE THREAD

**Issue by bricker** [fougere-mike/ExoPlayer#2]
Hey @fougere-mike thanks for making this fork. Out of the box I do see that the stream is able to be played from some point in the past. What I'm a little confused by is how seeking is supposed to be used. When applying your patch and then playing the stream, it starts from the beginning of the window — how do I start it from "now" (i.e. "live")? I can calculate the offset and then use `seekTo()` but it seems like I'm missing something.

Thanks again for the patch!

**Comment by Greg767** [comment]
Thanks for the patch and thanks for opening this. I am also interested to know how to achieve the seeking and reading from live point.

**Comment by fougere-mike** [comment]
The duration and position info is all relative to the start of the video, not the start of the window. 

If the window has slid forward and segments have been removed from the start of the playlist, the playlist's media sequence property should be updated to reflect that. That means, if there are truly only 2 segments in the playlist, but the media sequence is 2000, the duration reported by the player will be: (2000 + 2) \* segmentDuration.

So, to seek to live you should be able to do something like: `player.seekTo( player.getDuration() );` to seek to the very end of the playlist. 

For my own streams, I defend against seeking to the _real_ live edge because there might be a delay between seeking and the next segment actually being added to the playlist; that would result in a stall. I always stay at least 10 seconds behind the _real_ live position:

```
private void seekToInternal(long position) {
        // If this is a live stream, we will guard against seeking
        // to the _real_ end of the stream.
        if( isLiveStream() ) {
            long virtualLiveEdge = getDuration() - INTERVAL_FROM_LIVE_EDGE_MS;
            position = Math.min(position, virtualLiveEdge);
        }

        seekTo(position);
    }
```

Let me know if that's not working for you. Cheers!

**Comment by bricker** [comment]
@fougere-mike Great advice! Using your notes I was able to get everything working well. Thank you so much! I'll close this.

**Comment by bricker** [comment]
@fougere-mike I can seek to the live position but the stream still starts by default at 0 (i.e. beginning of the window). Is there a way to tell it to start from live, besides starting the stream and then seeking?

**Comment by fougere-mike** [comment]
Not presently, no. Although I can take a look at adding that if it's causing you problems.

**Comment by bricker** [comment]
I am going to do some work on it against your branch, I'll open a PR if there's anything worthwhile in there.

**Comment by fougere-mike** [comment]
Sounds good.

**Comment by fougere-mike** [comment]
There haven't been any updates here for a while -- closing for now.
